version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 8017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mySecret1!