version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sensorix_web
    networks:
      - sensorix_network
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongo:27017/sensorix_db

  mongo:
    image: mongo:latest
    container_name: sensorix_db
    networks:
      - sensorix_network
    ports:
      - "27017:27017"
    volumes:
      - mongo_volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: abcd1234!

volumes:
  mongo_volume:

networks:
  sensorix_network:
    driver: bridge
